### ISSUE TITLE
xrayR_for_V2board.sh

### ISSUE THREAD

**Issue by shangkouyou** [cdnf/shell#1]
[xrayR_for_V2board.sh](https://github.com/cdnf/shell/raw/master/xrayR_for_V2board.sh)
这个不能用Hysteria 你的博客为啥有这个呀

**Comment by cdnf** [comment]
> [xrayR_for_V2board.sh](https://github.com/cdnf/shell/raw/master/xrayR_for_V2board.sh) 这个不能用Hysteria 你的博客为啥有这个呀

没这种需求，可以自己加
